baseURL = 'https://evgenii-petrov.net/'
languageCode = 'en-US'
title = 'Blog of Evgenii Petrov'

[params.author]
name = 'Evgenii Petrov'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'

[mediaTypes]
  [mediaTypes.'application/atom+xml']
    suffixes = ['xml']

[outputFormats]
  [outputFormats.atom]
    mediaType = 'application/atom+xml'
    baseName = 'feed'
    isPlainText = false

[outputs]
  home = ['html', 'atom']

[markup]
  [markup.highlight]
    style = 'monokailight'
